services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=qYYmndrhAQd7cuf1
      - OPENVPN_PASSWORD=5EETr50ZdLRGZeMRCnYRldOSzQ1aiMrY
      - SERVER_COUNTRIES=Netherlands
      - FREE_ONLY=on
      # Timezone for accurate log times
      - TZ=GMT+6
      # Server list updater. 
      - UPDATER_PERIOD=24h
    ports:
      - "${PORT}:${PORT}"
      - "${BASE_URL_PORT}:${BASE_URL_PORT}"
      - "${RCLONE_SERVE_PORT}:${RCLONE_SERVE_PORT}"
      - "8070:8070"
      - "8090:8090"
    restart: always
  mltb:
    build: .
    container_name: mltb
    command: bash start.sh
    restart: on-failure
    env_file:
      - .env
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started 
