version: "3.9"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=luke.wilkins6@hotmail.com
      - OPENVPN_PASSWORD=Spongebob0604!
      - SERVER_REGIONS=Germany
      # Timezone for accurate log times
      - TZ=GMT+6
      # Server list updater. 
      - UPDATER_PERIOD=24h
    ports:
      - "${PORT}:${PORT}"
      - "${BASE_URL_PORT}:${BASE_URL_PORT}"
      - "${RCLONE_SERVE_PORT}:${RCLONE_SERVE_PORT}"
    restart: always
  app:
    build: .
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started 
    command: bash start.sh
    restart: on-failure
    env_file:
      - .env